# ports rule => project_no{2}service_no{3}
# ex. 30080 means project_no=30, service_no=080
version: '3.4'
services:
  zap: &zap
    image: zaproxy
    build: 
      context: .
    ports:
      - "8080:8080"
      - "8090:8090"
    working_dir: /zap
    command: zap-webswing.sh
    stdin_open: true
    tty: true
  